name: product-catalog-ci
on:
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v4

    - name: Setup Go 1.22
      uses: actions/setup-go@v4
      with:
        go-version: 1.22
    
    - name: Build 
      run: 
        cd src/product-catalog
        go mod download
        go build -o product-catalog-service main.go
      
    - name: unit tests
      run: |
        cd src/product-catalog
        go test ./...

  
  code-quality:
    runs-on: ubuntu-latest
    
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      
      - name : Run golangci-lint
        run: 
              go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
              golangci-lint run src/product-catalog/...
  
  docker:
     runs-on: ubuntu-latest
     needs: build
     steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: Install Docker
        uses: actions/setup-buildx-action@v2
      - name: login to Docker
        uses: docker/login-aciton@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Docker Push
        uses: docker/build-push-action@v6
        with: 
          context: src/product-catalog
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/product-catalog:${{github.run_id}} 

  Updatek8s:
      runs-on: ubuntu-latest
      needs: docker
      steps:
      - name: checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.TOKEN }}
      
      - name: Update tag in k8s Deployment Manifest
        run: | 
             sed -i 's/image: .*/image: ${{ secrets.DOCKER_USERNAME }}/product-catalog: ${{github.run_id}}/' kubernetes/productcatalog/depoy.yaml
      - name: Commit and push changes
        run: |
         git config --global user.email "ssaminder180@gmail.com"       
         git config --global user.name "Saminder Singh"
          git add kubernetes/productcatalog/depoy.yaml
          git commit -m "[CI]: Update Product Catalog Image tag"
          git
